"""add candidates table, employee relieving fields

Revision ID: 130bedd716b0
Revises: b46463d2fa4c
Create Date: 2026-07-28 16:12:08.440748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130bedd716b0'
down_revision = 'b46463d2fa4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=True),
    sa.Column('proposed_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('offer_date', sa.Date(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relieving_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('termination_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('termination_reason')
        batch_op.drop_column('relieving_date')

    op.drop_table('candidates')
    # ### end Alembic commands ###
