"""add employee documents

Revision ID: 319b9d9da008
Revises: 4c903f6f94bb
Create Date: 2026-08-04 23:24:19.894747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319b9d9da008'
down_revision = '4c903f6f94bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_documents')
    # ### end Alembic commands ###
