"""add company letterhead upload

Revision ID: 90451b04b45f
Revises: 130bedd716b0
Create Date: 2026-07-28 16:21:14.235547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90451b04b45f'
down_revision = '130bedd716b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('letterhead_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('letterhead_filename')

    # ### end Alembic commands ###
