"""add office location and attendance geo fields

Revision ID: aa7a09d0a2b4
Revises: 90451b04b45f
Create Date: 2026-08-03 14:13:17.579595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7a09d0a2b4'
down_revision = '90451b04b45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_in_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_in_distance_m', sa.Float(), nullable=True))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('office_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('office_longitude')
        batch_op.drop_column('office_latitude')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('check_in_distance_m')
        batch_op.drop_column('check_in_longitude')
        batch_op.drop_column('check_in_latitude')

    # ### end Alembic commands ###
