"""add audit notifications payroll status and checklists

Revision ID: e2773bec8876
Revises: 319b9d9da008
Create Date: 2026-08-04 23:36:58.299359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2773bec8876'
down_revision = '319b9d9da008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_accrued_month', sa.Integer(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payroll_runs_approved_by_employees', 'employees', ['approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payroll_runs_approved_by_employees', type_='foreignkey')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('status')

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_column('last_accrued_month')

    op.drop_table('notifications')
    op.drop_table('employee_checklist_items')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
